### PR TITLE
Website UX and styling fixes (Issue#55)

### PR DESCRIPTION
**Pull request by MartonDev**
Added a seperate docs route/page.
Changes include:
- Seperate docs route (added to routes.js too)
- Read docs from `assets/DOCUMENTATION.md`
- Removed docs from homepage and updated `router-link`s to redirect to /docs
- UX/UI update: added a custom section style to match the design language of the site
- Seperated markdown styles to it's own file with an scss/sass mixin, that can be used anywhere (`@include markdown();` in scss or `+markdown()` in sass), after importing (`@import "@/styles/Markdown.sass"`)
- Fixes: fixed "Repository" button showing up when there is no repo linked to the package, fixed endless loading when there are no versions released for a package (neither stable, nor latest; example: https://nest.land/package/ciphers)

### CODE REVIEW

**Comment by MartonDev** [comment]
This pull request basically finishes #55's second part

**Comment by MartonDev** [comment]
Screenshot: 
Screenshot_20200619_021622

**Comment by tbaumer22** [comment]
The preview deploy is failing because we have both a `yarn.lock` file and a `package-lock.json` file. After we're done editing code, I'm going to push a commit that removes `package-lock.json`.

**Comment by MartonDev** [comment]
@tbaumer22 I have removed `package-lock.json`. This pull request is ready for deployment

**Pull request merged**
