### PR TITLE
new badge

### LINKED ISSUE #102: new badge
nothing critical but the badge doesn't look that good.

I have made some examples that too are not very good but can be a starting point.

examples: [figma file](https://www.figma.com/file/BN2w0nSbJIxeSxP2PjwW9r/nest)

### PR DESCRIPTION
**Pull request by maximousblk**
### Changes from old badge
- no raster elements so renders equally
- ~1.3KB smaller (10.5KB now, 11.8KB original)
- cleaner and fits inside a frame

### Changes from the mockup
- rounded the corners
- reduced size to a badge height (from 60px to 30px)
- removed underline
- smaller frame size
---

closes #102

### CODE REVIEW

**Comment by maximousblk** [comment]
now it is smaller in size and looks better

**Comment by tbaumer22** [comment]
I was just about to ask if you could make it smaller! You beat me to it.

**Comment by tbaumer22** [comment]
Actually, if you view the preview deployment, the badge still looks a bit large. Could you shrink this to around 150px in width?

[https://nest-land-rb4p42or0.vercel.app/badge.svg](https://nest-land-rb4p42or0.vercel.app/badge.svg)

**Comment by maximousblk** [comment]
even smaller in size and in look

**Comment by maximousblk** [comment]
@tbaumer22 can we include large version too? in case anyone wants to put it on their website?

**Comment by tbaumer22** [comment]
Thank you for the contribution! The badge certainly needed an overhaul.

**Comment by tbaumer22** [comment]
We could include that. Just put it under a new file in the `public` folder of the site.

**Comment by maximousblk** [comment]
Added the large badge. Probably ready to merge.

**Pull request merged**
